name: Playwright Test Pipeline

on:
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}


        steps:

            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup NodeJS
              uses: actions/setup-node@v2
              with:
                  node-version: '20.x'

            - name: Cache Node Modules
              uses: actions/cache@v2
              with:
                path: ~/.npm
                key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                restore-keys: ${{ runner.os }}-node-

            - name: Install dependencies
              run: npm install

            - name: Install Playwright Browsers
              run: npx playwright install
            
            - name: Install Http Server
              run: npm install -g http-server
            
            - name: Start Http Server
              run: |
                nohup http-server -p 8080 &

            - name: Wait for the server to start
              run: |
                while ! curl -s http://127.0.0.1:8080; do
                  echo "Waiting for server to be ready"
                  sleep 1
                done
            
            - name: Run Playwright Tests
              run: npx playwright test tests/auth.spec.js
                

            
